---
- name: cleanup-env.yaml
  hosts: 127.0.0.1
  connection: local
  gather_facts: no
  vars_files:
    - job_vars/params.yaml

  tasks:
    - name: Include variables from job_vars/hyperc
      include_vars: "job_vars/hyperc"
      failed_when: False
      tags: always

    - name: Include vm-data
      include_vars:
        file: "./vm-data.yaml"
        name: vm_data

    - name: Get all neutron ports that need to be deleted
      set_fact:
        ports: "{{ vm_data.values() | map(attribute='ports') | map(attribute='management') | list }} + {{ vm_data.values() | map(attribute='ports') | map(attribute='dataplane') | list }}"