---
- name: prep-env.yaml
  hosts: 127.0.0.1
  connection: local
  vars_files:
    - job_vars/params.yaml

  tasks:
    - name: Include variables from job_vars/hyperc
      include_vars: "job_vars/hyperc"
      failed_when: False
      tags: always

    - include: tasks/boot.yaml
      with_items: "{{ vms }}"
      loop_control:
        loop_var: vm

    - copy:
        content: "{{ vm_data | to_nice_yaml }}"
        dest: "./vm-data.yaml"

    - name: Include vm-data variables file
      include_vars:
        file: "./vm-data.yaml"
        name: vm_data

    - name: Generate inventory file
      blockinfile:
        path: "./inv"
        create: yes
        block: |
          [{{ item.inventory_group }}]
          {{ vm_data[item.name].ports.management.port.fixed_ips[0].ip_address }} hostname={{ item.name }} {{ item.additional_params }}
        marker: "# {mark} {{ item.name }}"
      with_items: "{{ vms }}"